### PR TITLE
Eclipse AI Chatbot

### PR DESCRIPTION
**Pull request by Hugo-SEQUIER**

### CODE REVIEW

**Comment by julien-eclipse** [comment]
@Hugo-SEQUIER thanks for your PR. I made an update that fixes a typo around `program_address`. is the address listed still correct? it doesn't look like a standard program address and I don't see any tx history on mainnet / devnet / testnet so I wanted to confirm. is this a program address? any context here would be helpful, thank you!

**Comment by Hugo-SEQUIER** [comment]
Hello ! It's a mistake because this project doesn't required any contract. It's related to Eclipse because I use Irys (irys.xyz) to store data using Eclipse. 
I did this project to promote both Irys and Eclipse and show a way on how we can use easily AI, store conversation on a Blockchain (in this case Eclipse to help people to discover Eclipse)

**Comment by julien-eclipse** [comment]
@Hugo-SEQUIER that's awesome, love the project! right now I'm trying to figure out how to best handle this. in the future, I'm going to add automation to this repository to verify program builds and published IDLs. so this would break that. but I do want to promote cool projects like this. I'm thinking to create an `awesome-eclipse` repository ([like this](https://github.com/rust-unofficial/awesome-rust)) that would have it like other ecosystems do so we can highlight your project

for now I'm going to close this PR but I will tag you either here or in the new repository once we've figured out how we're going to handle this so we can promote your project how you'd like :)

**Comment by julien-eclipse** [comment]
@Hugo-SEQUIER it will live here if you want to create a PR, will determine the formatting and structure but can leave an initial suggestion for us to tweak once we determine how we want this repo to look

https://github.com/Eclipse-Laboratories-Inc/awesome-eclipse

**Comment by Hugo-SEQUIER** [comment]
Thanks for the feedback! I'll create a PR on the awesome-eclipse repo once I have access

**Comment by julien-eclipse** [comment]
@Hugo-SEQUIER the repo is now public, feel free to make a quick PR  - may ask you to reformat it as we set up contribution guidelines but will be a good starting point!

**Pull request closed without merging**
